version: "3"

services:
  backend:
    image: ghcr.io/ashanzzz/erpnext:version-15
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  create-site:
    image: ghcr.io/ashanzzz/erpnext:version-15
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench new-site frontend
        --mariadb-user-host-login-scope='%' 
        --admin-password=admin 
        --db-root-username=root 
        --db-root-password=admin 
        --install-app erpnext 
        --install-app hrms 
        --install-app payments;

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    volumes:
      - redis-queue-data:/data

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
EOF

# 4. 创建GitHub Actions配置文件
mkdir -p .github/workflows
cat > .github/workflows/docker-build.yml << 'EOF'
name: 构建并推送Docker镜像

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建和推送镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/erpnext:latest
            ghcr.io/${{ github.repository_owner }}/erpnext:version-15
