name: 构建并推送Docker镜像

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:      
  push:
    branches: [ main ]    
    paths:
      - 'apps.json'
      - '.github/workflows/docker-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Docker BuildX
        uses: docker/setup-buildx-action@v2
        
      - name: 缓存 Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 生成版本号
        id: version
        run: echo "VERSION=$(date +%Y%m%d)" >> $GITHUB_ENV
        
      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 构建和推送镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/erpnext:latest
            ghcr.io/${{ github.repository_owner }}/erpnext:version-15
            ghcr.io/${{ github.repository_owner }}/erpnext:${{ env.VERSION }}
