jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # Step 2: 获取版本号
      - name: 获取最新版本号
        run: |
          # 假设版本号存储在 apps.json 或通过 Git 的 tag 获取
          if [ -f "apps.json" ]; then
            export VERSION=$(jq -r '.[0].branch' apps.json | sed 's/version-//')
          else
            export VERSION=$(git describe --tags --always)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "最新版本号为: $VERSION"

      # Step 3: 生成 APPS_JSON_BASE64
      - name: 生成 APPS_JSON_BASE64
        run: |
          export APPS_JSON_BASE64=$(base64 -w 0 apps.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      # Step 4: 克隆 frappe_docker
      - name: 克隆 frappe_docker
        run: git clone https://github.com/frappe/frappe_docker

      # Step 5: 设置 Buildx
      - name: 设置 Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: 登录到 GitHub Container Registry
      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: 构建和推送镜像
      - name: 构建和推送镜像
        uses: docker/build-push-action@v3
        with:
          context: frappe_docker
          file: frappe_docker/images/layered/Containerfile
          push: true
          platforms: linux/amd64
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-${{ env.VERSION }}
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/erpnext:latest
            ghcr.io/${{ github.repository_owner }}/erpnext:version-${{ env.VERSION }}
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
