name: 构建并推送Docker镜像

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号午夜运行
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ main ]    # 推送到main分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: 输出开始信息
        run: |
          echo "=============== 构建开始 ==============="
          echo "开始时间: $(date)"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"

      - name: 检出代码
        uses: actions/checkout@v2

      - name: 验证构建文件
        run: |
          echo "=============== 文件验证 ==============="
          echo "检查 Dockerfile:"
          cat Dockerfile
          echo ""
          echo "检查 apps.json:"
          cat apps.json
          echo ""
          echo "验证 JSON 格式:"
          jq '.' apps.json || echo "JSON 格式错误!"

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 准备构建参数
        run: |
          echo "=============== 构建准备 ==============="
          echo "生成 Base64 编码:"
          APPS_JSON_BASE64=$(base64 -w 0 apps.json)
          echo "Base64 生成完成，长度: ${#APPS_JSON_BASE64}"
          echo "验证 Base64 内容:"
          echo "$APPS_JSON_BASE64" | base64 -d
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - name: 构建和推送镜像
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/erpnext:latest
            ghcr.io/${{ github.repository_owner }}/erpnext:version-15
          build-args: |
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}

      - name: 构建完成报告
        if: always()
        run: |
          echo "=============== 构建报告 ==============="
          echo "构建时间: $(date)"
          echo "构建状态: ${{ job.status }}"
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ 构建成功"
            echo "推送的镜像标签:"
            echo "- ghcr.io/${{ github.repository_owner }}/erpnext:latest"
            echo "- ghcr.io/${{ github.repository_owner }}/erpnext:version-15"
          else
            echo "❌ 构建失败"
            echo "请检查以下可能的问题:"
            echo "1. Dockerfile 中的命令路径是否正确"
            echo "2. bench 命令是否可用"
            echo "3. apps.json 格式是否正确"
            echo "4. 基础镜像是否存在问题"
          fi
