name: 推送 Docker 镜像到 Docker Hub

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
    paths:
      - 'apps.json'
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      # Step 1: 登录 GitHub Container Registry
      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: 拉取镜像从 GHCR
      - name: 拉取镜像从 GitHub Container Registry
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/erpnext:${{ github.sha }}
          docker pull ghcr.io/${{ github.repository_owner }}/erpnext:latest

      # Step 3: 登录 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: 为 Docker Hub 打标签
      - name: 为 Docker Hub 打标签
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/erpnext:${{ github.sha }} docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository_owner }}/erpnext:latest docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:latest

      # Step 5: 推送镜像到 Docker Hub
      - name: 推送镜像到 Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:${{ github.sha }}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:latest
