name: 构建并推送Docker镜像

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号运行
  workflow_dispatch:      
  push:
    branches: [ main ]    
    paths:
      - 'apps.json'
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      # Step 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v3
      
      # Step 2: 生成 APPS_JSON_BASE64
      - name: 生成 APPS_JSON_BASE64
        run: |
          echo "APPS_JSON_BASE64=$(base64 -w 0 apps.json)" >> $GITHUB_ENV
          
      # Step 3: 克隆 frappe_docker
      - name: 克隆 frappe_docker
        run: |
          git clone https://github.com/frappe/frappe_docker
          cd frappe_docker
          
      # Step 4: 设置 Docker Buildx
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Step 5: 登录 GitHub Container Registry
      - name: 登录 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 6: 构建并推送到 GitHub Container Registry
      - name: 构建并推送到 GHCR
        uses: docker/build-push-action@v3
        with:
          context: frappe_docker
          file: frappe_docker/images/layered/Containerfile
          push: true
          platforms: linux/amd64
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/erpnext:latest
            ghcr.io/${{ github.repository_owner }}/erpnext:version-15

      # Step 7: 登录到 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: 推送镜像到 Docker Hub
      - name: 推送镜像到 Docker Hub
        run: |
          # 先为 Docker Hub 打上合适的 tag
          docker tag ghcr.io/${{ github.repository_owner }}/erpnext:version-15 docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:version-15
          docker tag ghcr.io/${{ github.repository_owner }}/erpnext:latest docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:latest
          
          # 推送到 Docker Hub
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:version-15
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/erpnext:latest
